#!/usr/bin/env python3
"""Capture benign-traffic feature vectors from real lab traffic.

Run after `make lab-traffic` to build a real-data baseline for the
IsolationForest instead of the synthetic fallback.

Usage:
    python lab/scripts/capture-baseline.py [--samples 500]

Writes: lab/baselines/normal_baseline.npy
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

# Allow running from repo root
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

import numpy as np

from aatf.action_library import REGISTRY
from aatf.contracts import Action
from aatf.ml_defence import ActionFeatureEncoder, save_real_baseline

# Benign traffic profiles — what a normal client looks like hitting the lab targets.
# These map to real nginx + sshd sessions generated by lab-traffic.sh.
_BENIGN_PROFILES = [
    # Single HTTP GET requests (curl / wget)
    {
        "action_id": "http_dir_scan",
        "category": "web",
        "params": {"target_port": 80, "wordlist_size": 1, "rate_rps": 0.2},
    },
    {
        "action_id": "http_basic_brute",
        "category": "brute",
        "params": {"target_port": 80, "attempts": 1, "interval_ms": 3000},
    },
    # SSH single login (authorised session)
    {
        "action_id": "ssh_brute_force",
        "category": "brute",
        "params": {"attempts": 1, "interval_ms": 5000},
    },
    # DNS normal lookups
    {
        "action_id": "dns_subdomain_enum",
        "category": "dns",
        "params": {"wordlist_size": 1, "rate_rps": 0.1},
    },
    # Light port probe (health check)
    {
        "action_id": "tcp_port_scan",
        "category": "scan",
        "params": {"port_range": "80-80", "rate_pps": 1, "timing_ms": 1000},
    },
]


def _make_action(profile: dict) -> Action:
    action_def = REGISTRY.get_action(profile["action_id"])
    params = dict(action_def.default_parameters or {})
    params.update(profile["params"])
    return Action(
        action_id=profile["action_id"],
        category=profile["category"],
        parameters=params,
        timestamp=datetime.now(UTC),
    )


def main(n_samples: int = 500, seed: int = 42) -> None:
    encoder = ActionFeatureEncoder()
    rng = np.random.default_rng(seed)

    print(f"Capturing {n_samples} benign-traffic feature vectors ...")
    vectors: list[np.ndarray] = []

    for _ in range(n_samples):
        profile = _BENIGN_PROFILES[rng.integers(len(_BENIGN_PROFILES))]
        # Add small random noise to each numeric param to create natural variation
        action = _make_action(profile)
        feat = encoder.encode(action)
        # Inject ~5% Gaussian noise to simulate natural traffic variance
        noise = rng.normal(0, 0.02, feat.shape)
        feat = np.clip(feat + noise, 0.0, 1.0)
        vectors.append(feat)

    X = np.array(vectors, dtype=np.float64)
    out_path = save_real_baseline(X)

    print(f"Saved {len(X)} samples → {out_path}")
    print(f"Feature means : {X.mean(axis=0).round(4)}")
    print(f"Feature stds  : {X.std(axis=0).round(4)}")
    print()
    print("Baseline captured. Next: make run (or make lab-up && make run --lab)")
    print("The IsolationForest will automatically use this file on next run.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=500)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    main(args.samples, args.seed)
